/**
 * Wait Zone where new ships will arrive and be picked up by pilots.
 * Ships generated by the producer arrive here.
 * @author ccarn
 *
 */
public class ArrivalWaitZone extends WaitZone {

	public ArrivalWaitZone(int maxShips) {
		super(maxShips);
	}
	
	@Override
	public void arrivalMessage(Ship ship){
		System.out.println(ship + " arrives at arrival zone");
	}
	
	@Override
	public void departureMessage(Ship ship){
		// no departure message for arrival zone
	}
	
	@Override
	public synchronized void arrive (Ship ship) {
		super.arrive(ship);
		// notify pilots looking for a ship potentially!
		notifyAll();
	}
	
	/**
	 * Pilots call the arrival zone to request a ship. If none are avaialable, the pilot
	 * thread must wait()
	 * @return unpiloted Ship in the waiting zone
	 */
	public synchronized Ship allocatePilot() {
		while (findUnpilotedShip() == null) {
			try {
				wait();
			} catch (InterruptedException e) {
				e.printStackTrace();
			}
		}
		return findUnpilotedShip();
	}
	
	/**
	 * helper function to find if there are empty ships in the arrival zone.
	 * @return Ship without a pilot if one in the ships arraylist, else NULL.
	 */
	private Ship findUnpilotedShip() {
		for (Ship ship : ships) {
			if (ship.getPilot() == null) {
				return ship;
			}
		}
		return null;
	}
}
