/**
 * Wait Zone where new ships will arrive and be picked up by pilots.
 * Ships generated by the producer arrive here.
 * @author ccarn
 *
 */
public class ArrivalWaitZone extends WaitZone {

	/** create a new arrival waitzone with capacity for maxShips */
	public ArrivalWaitZone(int maxShips) {
		super(maxShips);
	}
	
	/**
	 * prints an arrival message to the console
	 * @param ship
	 */
	@Override
	public void arrivalMessage(Ship ship){
		System.out.println(ship + " arrives at arrival zone");
	}
	
	/**
	 * Adds ship to the waitzone if there's room, else makes the ship wait.
	 * Notifies pilots waiting on a ship.
	 * @param ship
	 */
	@Override
	public synchronized void arrive (Ship ship) {
		super.arrive(ship);
		// notify pilots looking for a ship potentially!
		notifyAll();
	}
	
	/**
	 * Pilots call the arrival zone to request a ship. If none are avaialable, the pilot
	 * thread must wait()
	 * @return unpiloted Ship in the waiting zone
	 */
	public synchronized Ship allocatePilot() {
		while (findUnpilotedShip() == null) {
			// no ships are in the arrival zone without a pilot
			try {
				wait();
			} catch (InterruptedException e) {
				e.printStackTrace();
			}
		}
		return findUnpilotedShip();
	}
	
	/**
	 * helper function to find if there are empty ships in the arrival zone.
	 * @return Ship without a pilot if one in the ships arraylist, else NULL.
	 */
	private Ship findUnpilotedShip() {
		for (Ship ship : ships) {
			if (ship.getPilot() == null) {
				// ship has no pilot, so pass it back
				return ship;
			}
		}
		// no unpiloted ships present
		return null;
	}
}
